### PR TITLE
Updated Facebook proxy to mirror Graph API endpoints

### LINKED ISSUE #22: Facebook Graph API proxy mostly unimplemented
Was just checking out the [graph API proxy](https://github.com/directactioneverywhere/server/tree/master/facebook) and noticed it has only one feature implemented.

Ideally you could use it exactly like the graph API and we wouldn't have to implement every feature.

I'm wanting to use this for my site, so it's definitely helpful.

### PR DESCRIPTION
**Pull request by alexgleason**
Fixes #22 and #23 

I have no way to test this, so if someone could kindly see how it works on the server that would be great.

Thanks. :smile:

### CODE REVIEW

**Comment by samertm** [comment]
Are there security concerns with making the facebook proxy completely transparent?

**Comment by alexgleason** [comment]
You can filter what content you want to allow users to query from inside of the Facebook dashboard, based on the provided secret key.

The only concern I have of releasing this publicly is that sites unassociated with DxE could potentially find this service and use it, taking up bandwidth on our server. But if the secret key only has "view" permissions set (not write), they won't be able to alter any data. I'm under the assumption it's set to view only, but probably worth double checking.

It may be possible to have a whitelist of allowed IP addresses. But I'm personally in favor of not implementing that unless it actually becomes a problem.

**Comment by samertm** [comment]
That still makes me kind of nervous. If we messed up something on the FB developer dashboard side, then we're exposing ourselves to a lot of potential damage. What do you think of just adding the endpoints that you need?

**Comment by alexgleason** [comment]
Oh wait, I'm wrong actually. This is safe.

Internally it always uses GET. You can't POST to it.

``` python
r = requests.get(
    'https://graph.facebook.com/{}'.format(path),
    params=payload
)
```

Even if you sent POST data to our servers it wouldn't do anything.

**Comment by mjperrone** [comment]
What problem does this solve?

**Comment by alexgleason** [comment]
@mjperrone Not sure I understand. In the readme you made for the /facebook directory you explained why mirroring the graph API makes sense. But currently you can't use the full graph API. It only allows you to query one thing.

The work I'm doing on [dxephilly.org](http://dxephilly.org/) needs to run in the browser (no server-side yet), but I want to use the graph API to pull out upcoming events. I had been pondering the best way to do that until I ran across this and was like "oh yeah, that solves my problem." I just needed to edit it to allow access to the full graph API.

**Comment by mjperrone** [comment]
This originally existed to add a counter to the dxe.com website which showed how many people rsvp'd to a specific event, so we built it to only cover that functionality. Website removed the counter a long time ago so this actually doesn't serve a purpose.

I was asking specifically about what problem this PR solves, and your second paragraph explains that pretty well. I'm with Samer in that I think we should limit it's functionality to just what we need, so the incentive for abuse is much less. Otherwise I think this is a great idea!

If you go [here](https://developers.facebook.com/tools/explorer/), you can play around with the API and get a short lived API key, which you can use to test the mini server locally.

**Comment by alexgleason** [comment]
Ah, alright cool.

Maybe we could have the API restricted only to DxE Facebook pages.

**Comment by mjperrone** [comment]
That's a good idea. Right now our canonical list of DxE Facebook pages is in airtable. We already have code that gets all the DxE FB links [here](https://github.com/directactioneverywhere/server/blob/master/dashboard/generate_dashboard_data.py#L71-L77) and code that turns the links into facebook object ids [here](https://github.com/directactioneverywhere/server/blob/master/dashboard/generate_dashboard_data.py#L41). It would probably be a bit slow for every request to this endpoint to have to make three HTTP requests (get airtable list, convert to ids, actually hit the fbapi with what the requester wanted) before returning, so I'd recommend caching both the list of DxE fb ids, and also caching the endpoint itself. For caching the endpoint, see [here](https://github.com/directactioneverywhere/server/pull/12/files) for caching the endpoint, and you can do something reasonable in memory for the fb ids.

Also, in order for browsers accessing your website to make async calls to dxetech.org, you'll have to change the server to add `Access-Control-Allow-Origin` to the response headers for that endpoint so the browser won't error out more context on that [here](https://en.wikipedia.org/wiki/Same-origin_policy). We already do that [here](https://github.com/directactioneverywhere/server/blob/master/build/conf/nginx.conf#L40-L42) so that should also be easy to add.

I typed that all up, but a more important question whose answer might make all this a lot easier, but why don't you have a server side to dxephilly? Y'all use a digitalocean droplet to host the site right? Why not run code on the droplet too?

**Comment by alexgleason** [comment]
Thanks for all the good info!

You're right that I could just deploy my own code. But I felt it's worth exploring a solution that could benefit everyone. :smile:

**Comment by alexgleason** [comment]
Closing since I now have [directactioneverywhere/dxephilly-api](https://github.com/directactioneverywhere/dxephilly-api). Thanks for the good suggestions. :smile:

**Pull request closed without merging**
